// @ts-check

import mdx from "@astrojs/mdx";
import preact from "@astrojs/preact";
import sitemap from "@astrojs/sitemap";
import { defineConfig, fontProviders } from "astro/config";
import rehypeExternalLinks from "rehype-external-links";

// https://astro.build/config
export default defineConfig({
    site: "https://the-ai-files.de",
    integrations: [mdx(), sitemap(), preact()],
    output: "static",
    server: {
        port: 3000,
    },
    markdown: {
        rehypePlugins: [rehypeExternalLinks, { target: "_blank" }],
    },
    fonts: [
        {
            provider: fontProviders.local(),
            name: "Atkinson",
            cssVariable: "--font-atkinson",
            fallbacks: ["sans-serif"],
            options: {
                variants: [
                    {
                        src: ["./src/assets/fonts/atkinson-regular.woff"],
                        weight: 400,
                        style: "normal",
                        display: "swap",
                    },
                    {
                        src: ["./src/assets/fonts/atkinson-bold.woff"],
                        weight: 700,
                        style: "normal",
                        display: "swap",
                    },
                ],
            },
        },
        {
            provider: fontProviders.fontsource(),
            name: "Roboto",
            cssVariable: "--font-roboto",
            styles: ["normal", "italic"],
            display: "swap",
            weights: [300, 400, 500, 700],
            formats: ["woff2"],
            unicodeRange: [
                "U+0000-00FF",
                "U+0131",
                "U+0152-0153",
                "U+02BB-02BC",
                "U+02C6",
                "U+02DA",
                "U+02DC",
                "U+0304",
                "U+0308",
                "U+0329",
                "U+2000-206F",
                "U+2074",
                "U+20AC",
                "U+2122",
                "U+2191",
                "U+2193",
                "U+2212",
                "U+2215",
                "U+FEFF",
                "U+FFFD",
            ],
        },
        {
            provider: fontProviders.fontsource(),
            name: "Lato",
            cssVariable: "--font-lato",
            styles: ["normal"],
            display: "swap",
            formats: ["woff2"],
            unicodeRange: [
                "U+0000-00FF",
                "U+0131",
                "U+0152-0153",
                "U+02BB-02BC",
                "U+02C6",
                "U+02DA",
                "U+02DC",
                "U+0304",
                "U+0308",
                "U+0329",
                "U+2000-206F",
                "U+2074",
                "U+20AC",
                "U+2122",
                "U+2191",
                "U+2193",
                "U+2212",
                "U+2215",
                "U+FEFF",
                "U+FFFD",
            ],
        },
        {
            provider: fontProviders.fontsource(),
            name: "Open Sans",
            cssVariable: "--font-open-sans",
            styles: ["normal"],
            display: "swap",
            formats: ["woff2"],
            unicodeRange: [
                "U+0000-00FF",
                "U+0131",
                "U+0152-0153",
                "U+02BB-02BC",
                "U+02C6",
                "U+02DA",
                "U+02DC",
                "U+0304",
                "U+0308",
                "U+0329",
                "U+2000-206F",
                "U+2074",
                "U+20AC",
                "U+2122",
                "U+2191",
                "U+2193",
                "U+2212",
                "U+2215",
                "U+FEFF",
                "U+FFFD",
            ],
        },
        {
            provider: fontProviders.fontsource(),
            name: "Playfair Display",
            cssVariable: "--font-playfair-display",
            styles: ["normal"],
            display: "swap",
            formats: ["woff2"],
            unicodeRange: [
                "U+0000-00FF",
                "U+0131",
                "U+0152-0153",
                "U+02BB-02BC",
                "U+02C6",
                "U+02DA",
                "U+02DC",
                "U+0304",
                "U+0308",
                "U+0329",
                "U+2000-206F",
                "U+2074",
                "U+20AC",
                "U+2122",
                "U+2191",
                "U+2193",
                "U+2212",
                "U+2215",
                "U+FEFF",
                "U+FFFD",
            ],
        },
    ],
});
