export const headlines = [
    "Wissenschaftler entdecken neues Mineral namens 'Lachstein' in Schokolade",
    "Kater verschläft neun Leben und erwacht als Hausbesitzer",
    "Stadt beschließt Verbot von Montagen - Dienstage als offizieller Faulenzertag eingeführt",
    "Bienen gründen eigene Honigbierbrauerei - Beliebtheit steigt unter Insekten",
    "Hund macht Yoga: Entwickelt neue Position 'nach unten schauender Dackel'",
    "Pinguine erobern die Stadt - Forderung nach kostenlosen Fischbrötchen erhoben",
    "Weltrekord gebrochen: Längste Pizza der Welt verschwunden - vermutlich aufgegessen",
    "Forscher entdecken geheime Unterwasserstadt voller quakender Fische",
    "Rentnergruppe gründet Flashmob-Chor: 'Gehstock-Gang' wird zum Internet-Hit",
    "Bürgermeister verkündet: Ab jetzt sind Schokoladeneis und Lachanfälle obligatorisch",
    "Neue Studie beweist: Schokolade ist das Geheimnis des Weltfriedens",
    "Entlaufene Gartenzwerge organisieren erfolgreichen Weltrekord im Baumklettern",
    "Kuh entpuppt sich als talentierte Balletttänzerin - Premiere von 'Schwanensee' begeistert Publikum",
    "Polizei fängt flüchtigen Flamingo ein - Vogel behauptet, er sei 'nur zum Spaß' geflogen",
    "Menschen überrascht: Schneckenrennen endet in dramatischem Fotofinish",
    "Katzenvideo geht viral - Kätzchen entdeckt Schwerkraft und beschließt, sie zu ignorieren",
    "Ältester Mann der Welt enthüllt sein Geheimnis: tägliches Frühstück aus Marshmallows und Cola",
    "Stadt verbietet Montagblues - stattdessen wird 'Macarena Monday' eingeführt",
    "Erfindung des Jahres: Roboter, der Pizza in kleinen mundgerechten Stücken füttert",
    "Hundetruppe gründet eigene Rockband - erstes Album 'Wuffing on the Moon' stürmt die Charts",
    "Mann überlebt sieben Meter Fall ohne seinen Kaffee zu verschütten",
    "Frau gewinnt im Lotto, findet aber ihre verlorenen Schlüssel vor dem Haus",
    "Weltrekord gebrochen: Jüngster Astronaut besteht Mars-Mission und verliert seinen ersten Milchzahn im All",
    "Wissenschaftler entdecken sprechende Eichhörnchen: 'Nüsse sind sooo lecker!'",
    "13-jähriger Junge eröffnet erfolgreiches Unternehmen für Schulschwänzen",
    "Geheimer Tunnel unter dem Stadtpark führt zu Schlaraffenland",
    "Frau gewinnt Wettschulden gegen Einhorn - fordert nun Flugreitstunden",
    "Familie lebt seit 20 Jahren mit Dinosaurier als Haustier",
    "Inselbewohner findet verlorene Stadt Atlantis hinter seinem Kühlschrank",
    "Katze löst mysteriösen Kriminalfall - enttarnt den Postboten als geheimen Hundeenthusiasten",
    "Steuern zahlen macht Spaß: Finanzamt eröffnet Achterbahn zur Steuererklärung",
    "Stadt beschließt Steuererleichterung für Einhörner und andere mythologische Wesen",
    "Steuern werden zum offiziellen Volkssport erklärt - erste Meisterschaft im Steuererklärungs-Marathon",
    "Steuerskandal: Ein Mann behauptet, seine Goldfische hätten ein eigenes Steuerparadies",
    "Forscher entdecken geheime Steuerquelle: Die Lachmünze im Kissen",
    "Steuergesetz wird durch neues Prinzip ersetzt: 'Zahle, was du möchtest' - Chaos bricht aus",
    "Finanzamt führt Steuervergünstigungen für Liegestütze und Bauchtanz ein",
    "Steuervermeidung à la Hollywood: Prominente lassen ihre Steuern von Schauspielern zahlen",
    "Steuerschnüffelhunde auf dem Vormarsch: Sie erschnüffeln unversteuerte Kekse",
    "Steuersünder versteckt sich in Torte - Beamte finden ihn dank dem Hinweis 'Mit Extra-Mehrwertsteuer'",
    "Außerirdisches Leben entdeckt! Marsrover findet Spuren von intelligenten Wesen.",
    "UFO-Sichtungen nehmen weltweit zu: Außerirdische Besucher oder Massenillusion?",
    "Geheime Regierungsdokumente enthüllen: Außerirdische haben Kontakt mit der Erde aufgenommen.",
    "Außerirdisches Raumschiff landet im Garten einer Familie - Begegnung der dritten Art!",
    "Forscher entdecken außerirdische Signale aus den Tiefen des Universums.",
    "Alien-Invasion oder Marketing-Stunt? Riesige Außerirdische-Skulptur erscheint auf Times Square.",
    "Alien-Technologie oder natürliche Phänomene? Rätselhafte Lichterscheinungen am Himmel.",
    "Außerirdische Abduktionen auf dem Vormarsch? Betroffene berichten von Begegnungen der unheimlichen Art.",
    "Neue Theorie: Außerirdische Zivilisationen könnten in Paralleluniversen existieren.",
    "Erste Kontaktaufnahme mit intelligentem außerirdischen Leben? SETI-Forscher empfangen mysteriöse Botschaft.",
    "Außerirdische bitten um Entschuldigung für Kornkreise - 'Wir waren nur im Spaßmodus!'",
    "UFO-Entführung geht schief: Aliens beschweren sich über 'menschliche Ineffizienz'",
    "Außerirdische Gastgeber geben zu: 'Wir haben vergessen, die Erdlinge einzuladen'",
    "Aliens landen auf dem falschen Planeten - 'Wo zum Teufel sind wir gelandet?'",
    "Klatsch aus dem All: Außerirdisches Paparazzi-Team erwischt Promi-Alien beim Sternenbrunch",
    "Alien-Touristen verärgert über langweilige Sehenswürdigkeiten auf der Erde - 'Wir wollten mehr als nur Pyramiden sehen!'",
    "Außerirdische Comedy-Show erobert den Kosmos - 'Es ist witziger als alles auf dem Mars!'",
    "Kleinkind entpuppt sich als Außerirdischer - 'Kein Wunder, dass er so gut mit Technologie umgeht!'",
    "Außerirdische Schönheitswettbewerb gewonnen von einem Blob - 'Es ist der Innere Wert, der zählt!'",
    "Aliens entdecken irdisches Fast Food - 'Wir haben endlich die ultimative fettige Leckerei gefunden!'",
    "Arbeitsplatz gesucht: Königreich sucht Hofnarren - Bewerber mit Clownserfahrung bevorzugt!",
    "Forscher enthüllen: Kaffeepausen steigern die Produktivität um 200% - Chef fordert nun stündliche Pausen!",
    "Skurriler Büro-Unfall: Mitarbeiter verwandelt sich versehentlich in Kaffeemaschine - Koffeinspiegel auf Rekordhoch!",
    "Revolutionäre Entdeckung: Faulheit ist ansteckend - Mitarbeiter organisieren 'Weltmeisterschaft im Nichtstun'!",
    "Karriere-Upgrade: Chef ersetzt Meetings durch spontane Tanzwettbewerbe - Wer hat den besten Moonwalk?",
    "Untersuchung zeigt: Büroklammern verschwinden in parallelen Dimensionen - Forscher starten Suche nach dem Büroklammer-Wurmloch!",
    "Studie enthüllt: Produktivität steigt mit dem Tragen von Einhorn-Hausschuhen - Unternehmen führt offizielle Dresscode-Änderung ein!",
    "Mitarbeiterin überlistet Kaffeemaschine mit 'Alexa' - 'Endlich kann ich meinen Kaffee per Sprachbefehl bestellen!'",
    "Eilmeldung: Bürogebäude von Papierflugzeugen bombardiert - Mitarbeiter fordern bessere Flugabwehrsysteme!",
    "Arbeitspensum auf Null gesetzt: Unternehmen führt täglichen Mittagsschlaf für alle Mitarbeiter ein - Nickerchen-Wettbewerb geplant!",
    "Wissenschaftliche Sensation: Forscher entdecken geheime Sprache der Laborratten - Dialoge über Käse und Experimentverweigerung enthüllt!",
    "Forschungsergebnis schockiert die Welt: Schokolade ist das Geheimnis zur Gewichtsabnahme - Naschen für eine schlanke Figur!",
    "Wissenschaftliche Studie enthüllt: Das Gehirn von Forschern besteht zu 90% aus Koffein!",
    "Revolutionärer Durchbruch: Forscher entwickeln Schwerkraft-abschaltenden Schalter - Weltmeisterschaft im schwebenden Kugelstoßen geplant!",
    "Forscher verwechseln DNA-Proben - Menschlicher Papagei entdeckt - Könnte fliegen und lustige Geräusche machen!",
    "Geheime Experimente enthüllt: Forscher entwickeln tanzenden Roboter, der 'Macarena' besser beherrscht als Menschen!",
    "Bahnbrechende Entdeckung: Forscher finden heraus, dass Lachen die beste Medizin ist - Krankenkassen planen Humor-Therapieabteilungen!",
    "Forscher bestätigen: Kuscheln mit Plüschtieren steigert das IQ-Level - Teddybär-Akademie öffnet für Studierende!",
    "Studie beweist: Forscher sind die besten Verkoster von Keksteig - Wettbewerb um den Goldenen Löffel gestartet!",
    "Geheime Forschung: Wissenschaftler arbeiten an der Erfindung einer Zeitmaschine - Meetings sollen rückwirkend vermeidbar sein!",
    "Forscherteam entdeckt neue Farbe im Regenbogen - 'Wolkenschafblau' sorgt für einen neuen Trend in der Modeindustrie!",
    "Experimentaler Durchbruch: Forscher erschaffen tanzende Tomaten - Ketchup-Disco eröffnet in Kürze!",
    "Wissenschaftler enthüllen: Die Quelle der ewigen Jugend ist ein Teller mit Spaghetti - Italienischer Rentner zum jüngsten Mann der Welt gekürt!",
    "Studie bestätigt: Forscher haben die weltweit höchste Schokoladenkonsumrate - 'Naschkatzen International' für den Nobelpreis nominiert!",
    "Neue Theorie: Forscher behaupten, dass Katzen in Wirklichkeit die wahren Herrscher der Welt sind - Miezen für den Weltherrschaftsgipfel eingeladen!",
    "Forscherin erfindet Schwerkraft-trotzenden Haarspray - Menschen mit Schwebehaaren im Aufwind der Modewelt!",
    "Wissenschaftlicher Durchbruch: Forscher entwickeln Schokoladen-teleportierendes Gerät - Naschen ohne Kalorien!",
    "Forscher entdecken die wahre Identität von Bigfoot - Er entpuppt sich als frustrierter Promi-Fußballer im Rentenalter!",
    "Studie bestätigt: Das Gehirn von Forschern ist ein Magnet für Schokolade - Neue Sicherheitsmaßnahmen in Laboren erforderlich!",
    "Forscherin entdeckt geheime Formel für unendliche Kaffeemenge - Weltrekord im Koffeinkonsum gebrochen!",
    "Studie bestätigt: Forscher haben das Geheimnis des perfekten Bad-Hair-Days gelöst - Shampoo-Hersteller verzweifelt!",
    "Wissenschaftlicher Durchbruch: Forscher erschaffen sprechende Haustiere - Katze und Papagei gründen erfolgreiches Comedy-Duo!",
    "Forscherteam entwickelt Gerät, das lästige Arbeitskollegen in Zimmerpflanzen verwandelt - Büros werden zum botanischen Garten!",
    "Experimentelle Studie: Forscher trainieren Goldfische zum Synchronschwimmen - Fisch-Olympiade geplant!",
    "Wissenschaftlicher Meilenstein: Forscher entdecken den ultimativen Schlüssel zum Glück - Eine Tüte Kartoffelchips pro Tag!",
    "Forscherin enthüllt: Die geheime Sprache der Kaffeemaschinen - 'Koffeeschüttel-Code' revolutioniert die Kaffeekultur!",
    "Revolutionäre Erfindung: Forscher entwickeln Schreibtisch mit eingebautem Nachmittagsschlaf - Produktivität erreicht neue Tiefs!",
    "Studie bestätigt: Forscher sind anfällig für Lachanfälle - Wissenschaftskonferenz endet mit einer Stunde Gelächter!",
    "Forscher erschaffen sprechenden Roboter, der bessere Witze erzählt als Comedians - Stand-up-Comedy vor dem Aus?",
];